'use client'

export const destinationsData: { [key: string]: any } = {
  'maasai-mara': {
    id: 'maasai-mara',
    slug: 'maasai-mara',
    name: 'Maasai Mara',
    country: 'Kenya',
    description:
      'Witness the raw power of the Great Migration with over 1.5 million wildebeest and 200,000 zebras crossing the Mara River. Experience the Big Five in one of Africa\'s most iconic reserves.',
    price: 155400,
    currency: 'KES',
    heroImage: '/images/mara-golden-sunset.jpg',
    breadcrumb: 'Kenya',
    rating: 4.9,
    ratingCount: 1000,
    duration: '5',
    tagline: 'Great Migration & Big Five',
    quote: 'In the Maasai Mara, you don\'t just see Africa—you feel it in every heartbeat.',
    quoteAuthor: 'Wildlife Documentary Explorer',
    animals: [
      {
        name: 'African Lion',
        emoji: '🦁',
        image: 'https://images.unsplash.com/photo-1484406566174-9da000fda645?w=100&h=100&fit=crop',
        note: '900+ resident lions · daily sightings',
        frequency: '✓ Very common',
      },
      {
        name: 'African Elephant',
        emoji: '🐘',
        image: 'https://images.unsplash.com/photo-1564489969458-b71d3b691f4e?w=100&h=100&fit=crop',
        note: 'Large herds near Mara River',
        frequency: '✓ Very common',
      },
      {
        name: 'Leopard',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1517849484589-c5400b1f4601?w=100&h=100&fit=crop',
        note: 'Often seen in fig trees along river',
        frequency: '✓ Common',
      },
      {
        name: 'Black Rhino',
        emoji: '🦏',
        image: 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=100&h=100&fit=crop',
        note: 'Protected conservancy zones',
        frequency: '◆ Occasional',
      },
      {
        name: 'African Buffalo',
        emoji: '🐃',
        image: 'https://images.unsplash.com/photo-1625253152195-803956ed05b3?w=100&h=100&fit=crop',
        note: 'Large herds throughout reserve',
        frequency: '✓ Very common',
      },
      {
        name: 'Nile Crocodile',
        emoji: '🐊',
        image: 'https://images.unsplash.com/photo-1608848461950-0fed8e7a4f4d?w=100&h=100&fit=crop',
        note: 'Wait at river crossing points',
        frequency: '✓ Common',
      },
      {
        name: 'Maasai Giraffe',
        emoji: '🦒',
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=100&h=100&fit=crop',
        note: 'Tallest subspecies · iconic silhouette',
        frequency: '✓ Very common',
      },
      {
        name: 'Hippopotamus',
        emoji: '🦛',
        image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=100&h=100&fit=crop',
        note: 'Massive pods in Mara River',
        frequency: '✓ Very common',
      },
      {
        name: 'Cheetah',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=100&h=100&fit=crop',
        note: 'Open plains — speed guaranteed',
        frequency: '✓ Common',
      },
      {
        name: 'Plains Zebra',
        emoji: '🦓',
        image: 'https://images.unsplash.com/photo-1612536315141-97e5d36bbbee?w=100&h=100&fit=crop',
        note: '200,000+ during migration',
        frequency: '✓ Very common',
      },
      {
        name: 'Wildebeest',
        emoji: '🦌',
        image: 'https://images.unsplash.com/photo-1618826411640-d6df44dd3f7a?w=100&h=100&fit=crop',
        note: '1.5 million during peak migration',
        frequency: '✓ Very common',
      },
      {
        name: 'African Wild Dog',
        emoji: '🐩',
        image: 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=100&h=100&fit=crop',
        note: 'Rare — bucket list sighting',
        frequency: '◆ Rare',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'First Sight of the Plains',
        subtitle: 'Arrival Day · Nairobi → Maasai Mara',
        description:
          'Fly from Nairobi (45 min bush flight) or drive through the Great Rift Valley (4.5 hrs scenic). Land on a red dirt airstrip in the middle of nowhere — and in that moment, you\'ll know you\'ve arrived somewhere real. Afternoon game drive en route to camp. Sundowners on the savanna. Dinner under the stars.',
        activities: ['Bush Flight', 'Afternoon Drive', 'Camp Check-in', 'Bush Sundowners', 'Dinner Included'],
      },
      {
        day: 2,
        title: 'The Hunt & the Herd',
        subtitle: 'Full Day · Deep into the Reserve',
        description:
          'Up at 5:30am. The air is cold and the grass is silver with dew. Your guide has been tracking a pride of lions since 4am. Today is a full Big Five day: lion, leopard in a fig tree, a herd of 300 buffalo, elephants at the river, and a cheetah sprints at 110km/h. You\'ll run out of camera space.',
        activities: ['Dawn Game Drive', 'Bush Breakfast', 'Big Five Tracking', 'River Crossing', 'Sunset Drive'],
      },
      {
        day: 3,
        title: 'The Great Migration Crossing',
        subtitle: 'Peak Season · June - August',
        description:
          'If visiting during migration season, witness one of nature\'s greatest spectacles: over 1 million wildebeest and 200,000 zebras crossing the Mara River. Our guides know exactly where and when it happens. The water boils with crocodiles. The ground trembles. You\'ll understand why this is on every explorer\'s bucket list.',
        activities: [
          'Migration Crossing',
          'River Viewpoints',
          'Photography Opportunities',
          'Naturalist Guide',
          'Picnic Lunch',
        ],
      },
      {
        day: 4,
        title: 'Hidden Moments & Cultural Immersion',
        subtitle: 'Optional · Maasai Village Visit',
        description:
          'Visit a traditional Maasai manyatta (village) to learn about the indigenous culture that has coexisted with wildlife for centuries. Meet warriors, learn about traditional beadwork, taste local food. Afternoon: back to camp for a relaxed game drive and reflection on your journey.',
        activities: [
          'Village Visit',
          'Cultural Exchange',
          'Beadwork Workshop',
          'Traditional Lunch',
          'Afternoon Drive',
        ],
      },
      {
        day: 5,
        title: 'The Goodbye Sunrise',
        subtitle: 'Departure Day',
        description:
          'One last early morning drive to catch the sunrise over the Mara. Your final moments in the reserve. Breakfast at camp, then the journey home. You\'ll leave with images, stories, and a wildness in your heart that will never fade.',
        activities: ['Final Game Drive', 'Sunrise Photography', 'Breakfast & Checkout', 'Bush Flight Home'],
      },
    ],
    included: [
      'All meals (breakfast, lunch, dinner, snacks)',
      'Expert professional safari guides',
      'All game drives (morning and afternoon)',
      ' 4x4 safari vehicle with popup roof',
      'Park entrance fees',
      'Bush flights (if selected)',
      '24/7 emergency support',
      'Travel insurance included',
    ],
    notIncluded: [
      'International flights',
      'Travel visas',
      'Personal travel insurance',
      'Tips and gratuities',
      'Alcoholic beverages',
      'Personal equipment (binoculars, camera)',
    ],
    lodge: {
      name: 'Maasai Mara Safari Lodge',
      type: 'Luxury Tented Camp',
      rating: '★★★★★',
      description:
        'Luxury tented accommodations with en-suite bathrooms and hot showers. Candlelit dinners under the stars, outdoor lounge areas, and modern amenities blend seamlessly with the natural environment.',
      amenities: [
        'Private en-suite bathrooms',
        'Hot water showers',
        'Comfortable king/twin beds',
        'Solar power & generators',
        'Fine dining restaurant',
        'Bar & lounge areas',
        'WiFi (limited)',
        'Medical facilities on-site',
      ],
    },
    bestTimeMonths: [
      { month: 'January', level: 'good' },
      { month: 'February', level: 'good' },
      { month: 'March', level: 'ok' },
      { month: 'April', level: 'low' },
      { month: 'May', level: 'low' },
      { month: 'June', level: 'peak' },
      { month: 'July', level: 'peak' },
      { month: 'August', level: 'peak' },
      { month: 'September', level: 'good' },
      { month: 'October', level: 'good' },
      { month: 'November', level: 'ok' },
      { month: 'December', level: 'good' },
    ],
    testimonials: [
      {
        quote: 'Absolutely life-changing experience. Saw all the Big Five, met incredible guides, and made memories that will last forever.',
        author: 'Sarah & Michael, USA',
        rating: 5,
      },
      {
        quote: 'The migration crossing was beyond our wildest dreams. Worth every penny and every minute of the long journey.',
        author: 'Emma, UK',
        rating: 5,
      },
      {
        quote: 'Professional, safe, and genuinely unforgettable. Our kids talk about the safari every single day.',
        author: 'James Family, Canada',
        rating: 5,
      },
    ],
  },
  'lake-naivasha': {
    id: 'lake-naivasha',
    slug: 'lake-naivasha',
    name: 'Lake Naivasha',
    country: 'Kenya',
    description: 'A serene freshwater lake surrounded by lush vegetation, rich birdlife, and peaceful water-based adventures.',
    price: 98500,
    currency: 'KES',
    heroImage: '/images/naivasha-lake-birds.jpg',
    breadcrumb: 'Kenya',
    rating: 4.7,
    ratingCount: 580,
    duration: '4',
    tagline: 'Birdwatching & Lake Adventures',
    quote: 'In the tranquility of Lake Naivasha, nature whispers its secrets to those who listen.',
    quoteAuthor: 'Nature Conservationist',
    animals: [
      {
        name: 'African Fish Eagle',
        emoji: '🦅',
        image: 'https://images.unsplash.com/photo-1540573133985-87b6da432665?w=100&h=100&fit=crop',
        note: 'Iconic lake raptors',
        frequency: '✓ Very common',
      },
      {
        name: 'Hippopotamus',
        emoji: '🦛',
        image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=100&h=100&fit=crop',
        note: 'Large pods in shallow waters',
        frequency: '✓ Very common',
      },
      {
        name: 'African Fish Eagle',
        emoji: '🦅',
        image: 'https://images.unsplash.com/photo-1540573133985-87b6da432665?w=100&h=100&fit=crop',
        note: 'Majestic lake raptors',
        frequency: '✓ Common',
      },
      {
        name: 'Cormorant',
        emoji: '🐦',
        image: 'https://images.unsplash.com/photo-1606576947614-f1cfef8c02be?w=100&h=100&fit=crop',
        note: 'Diving birds in morning light',
        frequency: '✓ Very common',
      },
      {
        name: 'Waterbuck',
        emoji: '🦌',
        image: 'https://images.unsplash.com/photo-1612536315141-97e5d36bbbee?w=100&h=100&fit=crop',
        note: 'Elegant shoreline grazers',
        frequency: '✓ Common',
      },
      {
        name: 'Vervet Monkey',
        emoji: '🐵',
        image: 'https://images.unsplash.com/photo-1582761487167-0cae3f5e1dd9?w=100&h=100&fit=crop',
        note: 'Playful troops on the shore',
        frequency: '✓ Very common',
      },
      {
        name: 'African Spoonbill',
        emoji: '🦢',
        image: 'https://images.unsplash.com/photo-1606576947614-f1cfef8c02be?w=100&h=100&fit=crop',
        note: 'Distinctive feeding birds',
        frequency: '✓ Common',
      },
      {
        name: 'Crowned Crane',
        emoji: '🦢',
        image: 'https://images.unsplash.com/photo-1606576947614-f1cfef8c02be?w=100&h=100&fit=crop',
        note: 'Graceful wetland dancers',
        frequency: '✓ Common',
      },
      {
        name: 'Giraffe',
        emoji: '🦒',
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=100&h=100&fit=crop',
        note: 'Acacia woodland browsers',
        frequency: '✓ Common',
      },
      {
        name: 'Cape Buffalo',
        emoji: '🐃',
        image: 'https://images.unsplash.com/photo-1625253152195-803956ed05b3?w=100&h=100&fit=crop',
        note: 'Small herds in valleys',
        frequency: '◆ Occasional',
      },
      {
        name: 'Zebra',
        emoji: '🦓',
        image: 'https://images.unsplash.com/photo-1612536315141-97e5d36bbbee?w=100&h=100&fit=crop',
        note: 'Grassland herds',
        frequency: '✓ Common',
      },
      {
        name: 'Impala',
        emoji: '🦌',
        image: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=100&h=100&fit=crop',
        note: 'Graceful acacia browsers',
        frequency: '✓ Common',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Welcome to the Lake',
        subtitle: 'Arrival Day · Nairobi → Lake Naivasha',
        description: 'Drive from Nairobi (1.5 hours) through the Great Rift Valley. Settle into your lakeside lodge overlooking the waters. Afternoon light boat ride to spot fish eagles and hippos. Sunset sundowner on the shore.',
        activities: ['Scenic Drive', 'Afternoon Boat Ride', 'Lodge Check-in', 'Sunset Cruise', 'Dinner'],
      },
      {
        day: 2,
        title: 'Birdwatcher\'s Paradise',
        subtitle: 'Full Day · Lake Exploration',
        description: 'Early morning boat expedition for birdwatching. Spot over 400 bird species including fish eagles, cormorants, and crowned cranes. Visit Crescent Island for guided walks among zebras and giraffes. Afternoon picnic on the shore.',
        activities: ['Dawn Boat Ride', 'Birdwatching', 'Crescent Island Walk', 'Picnic Lunch', 'Relaxation'],
      },
      {
        day: 3,
        title: 'Geological Wonders',
        subtitle: 'Optional · Hell\'s Gate National Park',
        description: 'Optional excursion to Hell\'s Gate for geothermal features and canyon hiking. See hot springs and geysers. Return to lake for sunset. Alternatively, explore local conservation projects.',
        activities: ['Hell\'s Gate Visit', 'Hot Springs', 'Canyon Hike', 'Geothermal Exploration', 'Sunset'],
      },
      {
        day: 4,
        title: 'Farewell to the Waters',
        subtitle: 'Departure Day',
        description: 'Final morning boat ride for last wildlife encounters. Breakfast overlooking the lake. Drive back to Nairobi with memories of serene waters and abundant birdlife.',
        activities: ['Final Boat Ride', 'Breakfast', 'Checkout', 'Scenic Return'],
      },
    ],
    included: [
      'All meals (breakfast, lunch, dinner, snacks)',
      'Expert naturalist guides',
      'All boat rides and water activities',
      'Park entrance fees',
      'Lodge accommodation',
      '24/7 emergency support',
    ],
    notIncluded: [
      'International flights',
      'Travel visas',
      'Personal travel insurance',
      'Tips and gratuities',
      'Alcoholic beverages',
    ],
    lodge: {
      name: 'Naivasha Waterside Lodge',
      type: 'Lakeside Resort',
      rating: '★★★★☆',
      description: 'Comfortable rooms with views over the tranquil lake. Excellent restaurant with fresh local cuisine. Water activities center for boat excursions.',
      amenities: [
        'Lakefront rooms with views',
        'Restaurant & bar',
        'Water activity center',
        'Swimming area',
        'Bird identification guide services',
        'Photography facilities',
        'WiFi available',
      ],
    },
    bestTimeMonths: [
      { month: 'January', level: 'good' },
      { month: 'February', level: 'peak' },
      { month: 'March', level: 'good' },
      { month: 'April', level: 'low' },
      { month: 'May', level: 'low' },
      { month: 'June', level: 'good' },
      { month: 'July', level: 'peak' },
      { month: 'August', level: 'peak' },
      { month: 'September', level: 'good' },
      { month: 'October', level: 'good' },
      { month: 'November', level: 'ok' },
      { month: 'December', level: 'good' },
    ],
    testimonials: [
      {
        quote: 'A peaceful getaway with incredible birdwatching. Over 200 species spotted in just 4 days!',
        author: 'David & Linda, Australia',
        rating: 5,
      },
      {
        quote: 'Perfect for bird lovers and families. The guides were incredibly knowledgeable.',
        author: 'Rachel, Germany',
        rating: 5,
      },
      {
        quote: 'A serene escape from the crowds. Lake Naivasha exceeded all expectations.',
        author: 'Mark Family, Singapore',
        rating: 4,
      },
    ],
  },
  'amboseli': {
    id: 'amboseli',
    slug: 'amboseli',
    name: 'Amboseli National Park',
    country: 'Kenya',
    description: 'Standing in the shadow of Mount Kilimanjaro with vast elephant herds and stunning vistas.',
    price: 135800,
    currency: 'KES',
    heroImage: '/images/amboseli-kilimanjaro.jpg',
    breadcrumb: 'Kenya',
    rating: 4.8,
    ratingCount: 720,
    duration: '5',
    tagline: 'Kilimanjaro Views & Elephant Herds',
    quote: 'Beneath Africa\'s highest peak, witness the majesty of the elephant in their natural kingdom.',
    quoteAuthor: 'Safari Photographer',
    animals: [
      {
        name: 'African Elephant',
        emoji: '🐘',
        image: 'https://images.unsplash.com/photo-1564489969458-b71d3b691f4e?w=100&h=100&fit=crop',
        note: 'Largest herds in Africa',
        frequency: '✓ Very common',
      },
      {
        name: 'Lion',
        emoji: '🦁',
        image: 'https://images.unsplash.com/photo-1484406566174-9da000fda645?w=100&h=100&fit=crop',
        note: 'Pride hunting at dawn',
        frequency: '✓ Common',
      },
      {
        name: 'Leopard',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1517849484589-c5400b1f4601?w=100&h=100&fit=crop',
        note: 'Acacia tree loungers',
        frequency: '◆ Occasional',
      },
      {
        name: 'African Spoonbill',
        emoji: '🦢',
        image: 'https://images.unsplash.com/photo-1606576947614-f1cfef8c02be?w=100&h=100&fit=crop',
        note: 'Wetland specialists',
        frequency: '✓ Common',
      },
      {
        name: 'Giraffe',
        emoji: '🦒',
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=100&h=100&fit=crop',
        note: 'Acacia tree browsers',
        frequency: '✓ Very common',
      },
      {
        name: 'Zebra',
        emoji: '🦓',
        image: 'https://images.unsplash.com/photo-1612536315141-97e5d36bbbee?w=100&h=100&fit=crop',
        note: 'Grassland herds',
        frequency: '✓ Very common',
      },
      {
        name: 'Wildebeest',
        emoji: '🦌',
        image: 'https://images.unsplash.com/photo-1618826411640-d6df44dd3f7a?w=100&h=100&fit=crop',
        note: 'Swamp populations',
        frequency: '✓ Common',
      },
      {
        name: 'Cheetah',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=100&h=100&fit=crop',
        note: 'Open plain hunters',
        frequency: '✓ Common',
      },
      {
        name: 'Maasai Giraffe',
        emoji: '🦒',
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=100&h=100&fit=crop',
        note: 'Kilimanjaro backdrop',
        frequency: '✓ Very common',
      },
      {
        name: 'Hippopotamus',
        emoji: '🦛',
        image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=100&h=100&fit=crop',
        note: 'Swampy waters',
        frequency: '✓ Common',
      },
      {
        name: 'African Fish Eagle',
        emoji: '🦅',
        image: 'https://images.unsplash.com/photo-1540573133985-87b6da432665?w=100&h=100&fit=crop',
        note: 'Sky rulers',
        frequency: '✓ Common',
      },
      {
        name: 'Secretary Bird',
        emoji: '🦅',
        image: 'https://images.unsplash.com/photo-1540573133985-87b6da432665?w=100&h=100&fit=crop',
        note: 'Ground stalkers',
        frequency: '✓ Occasional',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Kilimanjaro\'s Shadow',
        subtitle: 'Arrival Day · Nairobi → Amboseli',
        description: 'Fly to Amboseli airstrip (short flight from Nairobi). Check into your camp with stunning views of Mount Kilimanjaro. Afternoon game drive to see elephant herds. Sundowner on the plains.',
        activities: ['Bush Flight', 'Camp Welcome', 'Afternoon Game Drive', 'Sundowner', 'Dinner'],
      },
      {
        day: 2,
        title: 'Elephant Kingdom',
        subtitle: 'Full Day · Deep into the Park',
        description: 'Full day of elephant encounters. Visit Observation Hill for panoramic views. Watch herds of 100+ elephants. Afternoon: photograph with Kilimanjaro backdrop. Find lions, cheetahs, and buffalos.',
        activities: ['Dawn Drive', 'Observation Hill', 'Elephant Tracking', 'Photography', 'Evening Drive'],
      },
      {
        day: 3,
        title: 'Wetland Wonders',
        subtitle: 'Full Day · Swamp Exploration',
        description: 'Explore Amboseli\'s unique swamps filled with wildlife. Spot hippos, crocodiles, and water birds. Experience the unique ecosystem shaped by underground water from Kilimanjaro.',
        activities: ['Swamp Safari', 'Hippo Viewing', 'Bird Watching', 'Photo Sessions', 'Naturalist Talk'],
      },
      {
        day: 4,
        title: 'Cultural Encounter',
        subtitle: 'Half Day · Maasai Village',
        description: 'Visit a Maasai manyatta to learn about traditional culture. Interact with locals, learn about pastoralist lifestyle. Return to camp for final activities.',
        activities: ['Maasai Visit', 'Cultural Exchange', 'Village Walk', 'Afternoon Drive'],
      },
      {
        day: 5,
        title: 'Farewell to the Mountain',
        subtitle: 'Departure Day',
        description: 'Final morning game drive for last Kilimanjaro views and wildlife encounters. Breakfast at camp. Fly back to Nairobi with unforgettable memories.',
        activities: ['Final Drive', 'Breakfast', 'Bush Flight Home'],
      },
    ],
    included: [
      'All meals (breakfast, lunch, dinner, snacks)',
      'Expert guides',
      'All game drives',
      'Park fees',
      'Accommodation',
      '24/7 support',
    ],
    notIncluded: [
      'International flights',
      'Visas',
      'Personal insurance',
      'Gratuities',
      'Beverages',
    ],
    lodge: {
      name: 'Amboseli Kilimanjaro Lodge',
      type: 'Luxury Camp',
      rating: '★★★★★',
      description: 'Spacious tented rooms with en-suite bathrooms overlooking the park and Kilimanjaro. Gourmet meals and premium amenities.',
      amenities: [
        'En-suite tented rooms',
        'Hot water showers',
        'Kilimanjaro views',
        'Fine dining',
        'Bar & lounge',
        'WiFi available',
        'Photography facilities',
      ],
    },
    bestTimeMonths: [
      { month: 'January', level: 'peak' },
      { month: 'February', level: 'peak' },
      { month: 'March', level: 'good' },
      { month: 'April', level: 'low' },
      { month: 'May', level: 'low' },
      { month: 'June', level: 'good' },
      { month: 'July', level: 'peak' },
      { month: 'August', level: 'peak' },
      { month: 'September', level: 'good' },
      { month: 'October', level: 'good' },
      { month: 'November', level: 'ok' },
      { month: 'December', level: 'peak' },
    ],
    testimonials: [
      {
        quote: 'Kilimanjaro as a backdrop to endless elephant herds — absolutely magical!',
        author: 'Jennifer & Robert, USA',
        rating: 5,
      },
      {
        quote: 'The guides\' knowledge about elephant behavior was exceptional. Worth every shilling.',
        author: 'Klaus, Germany',
        rating: 5,
      },
      {
        quote: 'Unique ecosystem and incredible photography opportunities at every turn.',
        author: 'Photography Club, France',
        rating: 5,
      },
    ],
  },
  'tsavo': {
    id: 'tsavo',
    slug: 'tsavo',
    name: 'Tsavo National Park',
    country: 'Kenya',
    description: 'Kenya\'s largest park with rugged beauty, the iconic red earth, and diverse wildlife thriving in extreme conditions.',
    price: 118900,
    currency: 'KES',
    heroImage: '/images/tsavo-red-earth.jpg',
    breadcrumb: 'Kenya',
    rating: 4.6,
    ratingCount: 490,
    duration: '4',
    tagline: 'Red Earth & Wild Encounters',
    quote: 'In Tsavo\'s vast wilderness, nature reveals its most authentic and untamed self.',
    quoteAuthor: 'Wilderness Explorer',
    animals: [
      {
        name: 'Lion',
        emoji: '🦁',
        image: 'https://images.unsplash.com/photo-1484406566174-9da000fda645?w=100&h=100&fit=crop',
        note: 'Red-maned lions unique to Tsavo',
        frequency: '✓ Common',
      },
      {
        name: 'African Elephant',
        emoji: '🐘',
        image: 'https://images.unsplash.com/photo-1564489969458-b71d3b691f4e?w=100&h=100&fit=crop',
        note: 'Red dust-covered herds',
        frequency: '✓ Very common',
      },
      {
        name: 'Black Rhino',
        emoji: '🦏',
        image: 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=100&h=100&fit=crop',
        note: 'Protected populations',
        frequency: '◆ Occasional',
      },
      {
        name: 'Leopard',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1517849484589-c5400b1f4601?w=100&h=100&fit=crop',
        note: 'Rocky outcrop dwellers',
        frequency: '◆ Occasional',
      },
      {
        name: 'Buffalo',
        emoji: '🐃',
        image: 'https://images.unsplash.com/photo-1625253152195-803956ed05b3?w=100&h=100&fit=crop',
        note: 'Large herds at watering holes',
        frequency: '✓ Common',
      },
      {
        name: 'Giraffe',
        emoji: '🦒',
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=100&h=100&fit=crop',
        note: 'Acacia feeding',
        frequency: '✓ Very common',
      },
      {
        name: 'Zebra',
        emoji: '🦓',
        image: 'https://images.unsplash.com/photo-1612536315141-97e5d36bbbee?w=100&h=100&fit=crop',
        note: 'Large plains herds',
        frequency: '✓ Very common',
      },
      {
        name: 'Cheetah',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=100&h=100&fit=crop',
        note: 'Speed on open plains',
        frequency: '✓ Common',
      },
      {
        name: 'Hippopotamus',
        emoji: '🦛',
        image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=100&h=100&fit=crop',
        note: 'Galana River pods',
        frequency: '✓ Common',
      },
      {
        name: 'Nile Crocodile',
        emoji: '🐊',
        image: 'https://images.unsplash.com/photo-1608848461950-0fed8e7a4f4d?w=100&h=100&fit=crop',
        note: 'Ancient river predators',
        frequency: '✓ Common',
      },
      {
        name: 'Gerenuk',
        emoji: '🦌',
        image: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=100&h=100&fit=crop',
        note: 'Long-necked browsersUnique to region',
        frequency: '✓ Occasional',
      },
      {
        name: 'Secretary Bird',
        emoji: '🦅',
        image: 'https://images.unsplash.com/photo-1540573133985-87b6da432665?w=100&h=100&fit=crop',
        note: 'Snake hunters on the savanna',
        frequency: '✓ Occasional',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Enter the Red Earth',
        subtitle: 'Arrival Day · Nairobi → Tsavo',
        description: 'Drive through changing landscapes as you enter Tsavo\'s distinctive red earth environment. Settlement at camp with views over the vast plains. Afternoon game drive. Dinner under stars.',
        activities: ['Scenic Drive', 'Camp Welcome', 'Afternoon Drive', 'Sundowner', 'Dinner'],
      },
      {
        day: 2,
        title: 'Mane Encounters',
        subtitle: 'Full Day · Lion Territory',
        description: 'Track the legendary red-maned lions of Tsavo. Explore rocky kopjes where leopards hide. Visit watering holes at dawn for maximum wildlife concentration. Photography of elephants against red dust.',
        activities: ['Dawn Drive', 'Lion Tracking', 'Kopje Exploration', 'Photography', 'Evening Drive'],
      },
      {
        day: 3,
        title: 'Water & Wilderness',
        subtitle: 'Full Day · River Safari',
        description: 'Explore the Galana River and its ecosystems. Spot hippos, crocodiles, and water birds. Visit Lugard Falls. Experience the untamed essence of Tsavo.',
        activities: ['River Exploration', 'Hippo Safari', 'Lugard Falls', 'Birdwatching', 'Photography'],
      },
      {
        day: 4,
        title: 'Farewell to the Wild',
        subtitle: 'Departure Day',
        description: 'Final morning drive through the red landscape. Breakfast and checkout. Return to Nairobi carrying the spirit of untamed Africa.',
        activities: ['Final Game Drive', 'Breakfast', 'Return Drive'],
      },
    ],
    included: [
      'All meals',
      'Expert guides',
      'Game drives',
      'Park fees',
      'Accommodation',
      'Emergency support',
    ],
    notIncluded: [
      'International flights',
      'Visas',
      'Insurance',
      'Gratuities',
      'Drinks',
    ],
    lodge: {
      name: 'Tsavo Red Earth Lodge',
      type: 'Safari Camp',
      rating: '★★★★☆',
      description: 'Comfortable accommodations in the heart of Tsavo with authentic safari atmosphere. Traditional meals and expert guides.',
      amenities: [
        'Spacious tented rooms',
        'En-suite bathrooms',
        'Traditional dining',
        'Fireplace lounge',
        'Bar & terrace',
        'Wildlife information center',
        'Photography guides available',
      ],
    },
    bestTimeMonths: [
      { month: 'January', level: 'good' },
      { month: 'February', level: 'peak' },
      { month: 'March', level: 'ok' },
      { month: 'April', level: 'low' },
      { month: 'May', level: 'low' },
      { month: 'June', level: 'good' },
      { month: 'July', level: 'peak' },
      { month: 'August', level: 'peak' },
      { month: 'September', level: 'good' },
      { month: 'October', level: 'good' },
      { month: 'November', level: 'ok' },
      { month: 'December', level: 'good' },
    ],
    testimonials: [
      {
        quote: 'Raw, untamed Africa at its finest. The red-maned lions were unforgettable.',
        author: 'Marcus & Angela, South Africa',
        rating: 5,
      },
      {
        quote: 'Vastness and wilderness combined perfectly. An authentic safari experience.',
        author: 'Tom, New Zealand',
        rating: 4,
      },
      {
        quote: 'The unique landscape and wildlife encounters make Tsavo truly special.',
        author: 'Safari Group, UK',
        rating: 5,
      },
    ],
  },
}
