'use client'

export const destinationsData: { [key: string]: any } = {
  '1': {
    id: '1',
    name: 'Maasai Mara',
    country: 'Kenya',
    description:
      'Experience the raw power of Africa\'s iconic wildlife in their natural habitat. The Great Migration is a sight to behold.',
    price: 155400,
    currency: 'KES',
    heroImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lion%20country-MhAKVw2p8iOKDXDRZbQj97qQaR0QZH.jpg',
    breadcrumb: 'Kenya',
    rating: 4.9,
    ratingCount: 1000,
    duration: '5',
    tagline: 'Great Migration & Big Five',
    quote: 'In the Maasai Mara, you don\'t just see Africa—you feel it in every heartbeat.',
    quoteAuthor: 'Wildlife Documentary Explorer',
    animals: [
      {
        name: 'African Lion',
        emoji: '🦁',
        image: 'https://images.unsplash.com/photo-1484406566174-9da000fda645?w=100&h=100&fit=crop',
        note: '900+ resident lions · daily sightings',
        frequency: '✓ Very common',
      },
      {
        name: 'African Elephant',
        emoji: '🐘',
        image: 'https://images.unsplash.com/photo-1564489969458-b71d3b691f4e?w=100&h=100&fit=crop',
        note: 'Large herds near Mara River',
        frequency: '✓ Very common',
      },
      {
        name: 'Leopard',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1517849484589-c5400b1f4601?w=100&h=100&fit=crop',
        note: 'Often seen in fig trees along river',
        frequency: '✓ Common',
      },
      {
        name: 'Black Rhino',
        emoji: '🦏',
        image: 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=100&h=100&fit=crop',
        note: 'Protected conservancy zones',
        frequency: '◆ Occasional',
      },
      {
        name: 'African Buffalo',
        emoji: '🐃',
        image: 'https://images.unsplash.com/photo-1625253152195-803956ed05b3?w=100&h=100&fit=crop',
        note: 'Large herds throughout reserve',
        frequency: '✓ Very common',
      },
      {
        name: 'Nile Crocodile',
        emoji: '🐊',
        image: 'https://images.unsplash.com/photo-1608848461950-0fed8e7a4f4d?w=100&h=100&fit=crop',
        note: 'Wait at river crossing points',
        frequency: '✓ Common',
      },
      {
        name: 'Maasai Giraffe',
        emoji: '🦒',
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=100&h=100&fit=crop',
        note: 'Tallest subspecies · iconic silhouette',
        frequency: '✓ Very common',
      },
      {
        name: 'Hippopotamus',
        emoji: '🦛',
        image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=100&h=100&fit=crop',
        note: 'Massive pods in Mara River',
        frequency: '✓ Very common',
      },
      {
        name: 'Cheetah',
        emoji: '🐆',
        image: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=100&h=100&fit=crop',
        note: 'Open plains — speed guaranteed',
        frequency: '✓ Common',
      },
      {
        name: 'Plains Zebra',
        emoji: '🦓',
        image: 'https://images.unsplash.com/photo-1612536315141-97e5d36bbbee?w=100&h=100&fit=crop',
        note: '200,000+ during migration',
        frequency: '✓ Very common',
      },
      {
        name: 'Wildebeest',
        emoji: '🦌',
        image: 'https://images.unsplash.com/photo-1618826411640-d6df44dd3f7a?w=100&h=100&fit=crop',
        note: '1.5 million during peak migration',
        frequency: '✓ Very common',
      },
      {
        name: 'African Wild Dog',
        emoji: '🐩',
        image: 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=100&h=100&fit=crop',
        note: 'Rare — bucket list sighting',
        frequency: '◆ Rare',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'First Sight of the Plains',
        subtitle: 'Arrival Day · Nairobi → Maasai Mara',
        description:
          'Fly from Nairobi (45 min bush flight) or drive through the Great Rift Valley (4.5 hrs scenic). Land on a red dirt airstrip in the middle of nowhere — and in that moment, you\'ll know you\'ve arrived somewhere real. Afternoon game drive en route to camp. Sundowners on the savanna. Dinner under the stars.',
        activities: ['Bush Flight', 'Afternoon Drive', 'Camp Check-in', 'Bush Sundowners', 'Dinner Included'],
      },
      {
        day: 2,
        title: 'The Hunt & the Herd',
        subtitle: 'Full Day · Deep into the Reserve',
        description:
          'Up at 5:30am. The air is cold and the grass is silver with dew. Your guide has been tracking a pride of lions since 4am. Today is a full Big Five day: lion, leopard in a fig tree, a herd of 300 buffalo, elephants at the river, and a cheetah sprints at 110km/h. You\'ll run out of camera space.',
        activities: ['Dawn Game Drive', 'Bush Breakfast', 'Big Five Tracking', 'River Crossing', 'Sunset Drive'],
      },
      {
        day: 3,
        title: 'The Great Migration Crossing',
        subtitle: 'Peak Season · June - August',
        description:
          'If visiting during migration season, witness one of nature\'s greatest spectacles: over 1 million wildebeest and 200,000 zebras crossing the Mara River. Our guides know exactly where and when it happens. The water boils with crocodiles. The ground trembles. You\'ll understand why this is on every explorer\'s bucket list.',
        activities: [
          'Migration Crossing',
          'River Viewpoints',
          'Photography Opportunities',
          'Naturalist Guide',
          'Picnic Lunch',
        ],
      },
      {
        day: 4,
        title: 'Hidden Moments & Cultural Immersion',
        subtitle: 'Optional · Maasai Village Visit',
        description:
          'Visit a traditional Maasai manyatta (village) to learn about the indigenous culture that has coexisted with wildlife for centuries. Meet warriors, learn about traditional beadwork, taste local food. Afternoon: back to camp for a relaxed game drive and reflection on your journey.',
        activities: [
          'Village Visit',
          'Cultural Exchange',
          'Beadwork Workshop',
          'Traditional Lunch',
          'Afternoon Drive',
        ],
      },
      {
        day: 5,
        title: 'The Goodbye Sunrise',
        subtitle: 'Departure Day',
        description:
          'One last early morning drive to catch the sunrise over the Mara. Your final moments in the reserve. Breakfast at camp, then the journey home. You\'ll leave with images, stories, and a wildness in your heart that will never fade.',
        activities: ['Final Game Drive', 'Sunrise Photography', 'Breakfast & Checkout', 'Bush Flight Home'],
      },
    ],
    included: [
      'All meals (breakfast, lunch, dinner, snacks)',
      'Expert professional safari guides',
      'All game drives (morning and afternoon)',
      ' 4x4 safari vehicle with popup roof',
      'Park entrance fees',
      'Bush flights (if selected)',
      '24/7 emergency support',
      'Travel insurance included',
    ],
    notIncluded: [
      'International flights',
      'Travel visas',
      'Personal travel insurance',
      'Tips and gratuities',
      'Alcoholic beverages',
      'Personal equipment (binoculars, camera)',
    ],
    lodge: {
      name: 'Maasai Mara Safari Lodge',
      type: 'Luxury Tented Camp',
      rating: '★★★★★',
      description:
        'Luxury tented accommodations with en-suite bathrooms and hot showers. Candlelit dinners under the stars, outdoor lounge areas, and modern amenities blend seamlessly with the natural environment.',
      amenities: [
        'Private en-suite bathrooms',
        'Hot water showers',
        'Comfortable king/twin beds',
        'Solar power & generators',
        'Fine dining restaurant',
        'Bar & lounge areas',
        'WiFi (limited)',
        'Medical facilities on-site',
      ],
    },
    bestTimeMonths: [
      { month: 'January', level: 'good' },
      { month: 'February', level: 'good' },
      { month: 'March', level: 'ok' },
      { month: 'April', level: 'low' },
      { month: 'May', level: 'low' },
      { month: 'June', level: 'peak' },
      { month: 'July', level: 'peak' },
      { month: 'August', level: 'peak' },
      { month: 'September', level: 'good' },
      { month: 'October', level: 'good' },
      { month: 'November', level: 'ok' },
      { month: 'December', level: 'good' },
    ],
    testimonials: [
      {
        quote: 'Absolutely life-changing experience. Saw all the Big Five, met incredible guides, and made memories that will last forever.',
        author: 'Sarah & Michael, USA',
        rating: 5,
      },
      {
        quote: 'The migration crossing was beyond our wildest dreams. Worth every penny and every minute of the long journey.',
        author: 'Emma, UK',
        rating: 5,
      },
      {
        quote: 'Professional, safe, and genuinely unforgettable. Our kids talk about the safari every single day.',
        author: 'James Family, Canada',
        rating: 5,
      },
    ],
  },
}
